function SPEDRUN(){

    Alert("SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN SPEDRUN i like my spedruns drippy SPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUN i like my spedruns drippy SPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUNSPEDRUN SPEDRUN");


}